language: node_js
node_js:
  - "12"
cache: npm
services:
  - docker

branches:
  only:
    - master

before_install:
  - npm i -g npm@latest

script:
  - bash ./travis/install.sh
  - bash ./travis/build.sh
  - bash ./travis/tag.sh
  - bash ./travis/publish.sh

before_deploy:
  - bash ./travis/publish.sh
