dist: bionic
language: node_js
node_js:
  - "12"
cache: npm
env:
  matrix:
    - ARCH=amd64
    - ARCH=arm64v8

sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - npm i -g npm@latest

script:
  - bash ./travis/install.sh
  - bash ./travis/build.sh
  - bash ./travis/tag.sh
  - bash ./travis/publish.sh

before_deploy:
  - bash ./travis/publish.sh
