dist: bionic
language: node_js
node_js:
  - "12"
cache: npm
env:
  matrix:
    - ARCH=amd64
    - ARCH=arm64v8
    - ARCH=native

sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - npm i -g npm@latest
  - npm i -g pkg
  - dpkg --add-architecture i386
  - apt-get update
  - apt-get install -y libc6:i386 libstdc++6:i386

script:
  - if [ "$ARCH" = "amd64" ]; then bash ./travis/docker.sh; fi
  - if [ "$ARCH" = "arm64v8" ]; then bash ./travis/docker.sh; fi
  - if [ "$ARCH" = "native" ]; then bash ./travis/native.sh; fi

before_deploy:
  - bash ./travis/publish.sh
