language: node_js
cache: npm
services:
  - docker

branches:
  only:
    - master

env:
  - VERSION="$(npx -c 'echo "$npm_package_version"')"

before_install:
  - npm i -g npm@latest

script:
  - bash ./travis/install.sh
  - bash ./travis/build.sh
  - bash ./travis/tag.sh

before_deploy:
  - bash ./travis/publish.sh
