version: '3'
services:
  entry:
    container_name: entry
    build:
      context: .
      dockerfile: docker/develop/entry/Dockerfile
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/develop/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/develop/backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DB=/usr/src/app/db
