version: '3'
services:
  entry:
    container_name: entry
    image: bvdk2019/entry
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
  frontend:
    container_name: frontend
    image: bvdk2019/frontend
  backend:
    container_name: backend
    image: bvdk2019/backend
    volumes:
      - /var/data/bvdk/db:/usr/src/app/db
    environment:
      - DB=/usr/src/app/db
