version: '3'
services:
  entry:
    container_name: entry
    image: bvdk2019/entry
    ports:
      - 80:80
  frontend:
    container_name: frontend
    image: bvdk2019/frontend
    volumes:
      - ./frontend:/usr/src/app
  backend:
    container_name: backend
    image: bvdk2019/backend
    volumes:
      - ./backend:/usr/src/app
      - /var/data/bvdk/db:/usr/src/app/db
    environment:
      - DB=/usr/src/app/db
